=== jvandervort/RecipeCommander/src/main/resources/recipe_book.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
	<xsd:element name = "jRecipeBook">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "Recipe" maxOccurs='unbounded'/>
			</xsd:sequence>
			<xsd:attribute name="Name" type="xsd:string"/>
			<xsd:attribute name="ModDate" type="xsd:string"/>
			<xsd:attribute name="UUID" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Recipe">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "IngredientList" minOccurs='0' maxOccurs='unbounded'/>
				<xsd:element ref = "ProcessList" minOccurs='0' maxOccurs='unbounded'/>
				<xsd:element ref = "Comments" minOccurs='0' maxOccurs='unbounded'/>
				<xsd:element name = "Picture" type="xsd:string" minOccurs='0' maxOccurs='unbounded'/>
			</xsd:sequence>
			<xsd:attribute name="Name" type="xsd:string"/>
			<xsd:attribute name="Source" type="xsd:string"/>
			<xsd:attribute name="Chapter" type="xsd:string"/>
			<xsd:attribute name="Submitter" type="xsd:string"/>
			<xsd:attribute name="Cat" type="xsd:string"/>
			<xsd:attribute name="SubCat" type="xsd:string"/>
			<xsd:attribute name="Origin" type="xsd:string"/>
			<xsd:attribute name="ModDate" type="xsd:string"/>
                        <xsd:attribute name="recipe_id" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "IngredientList">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "Ingredient" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "ProcessList">
		<xsd:complexType>
   		<xsd:simpleContent>
    			<xsd:extension base="xsd:string">
					<xsd:attribute name="prep_time" type="xsd:string"/>
					<xsd:attribute name="total_time" type="xsd:string"/>
				</xsd:extension>
   		</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Comments" type = "xsd:string"/>
	<xsd:element name = "Ingredient">
		<xsd:complexType>
			<xsd:attribute name="Name" type="xsd:string"/>
			<xsd:attribute name="Amount" type="xsd:string"/>
			<xsd:attribute name="Units" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== jvandervort/RecipeCommander/src/test/TestXmlBook.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<jRecipeBook
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation='recipe_book.xsd'
Name="Test Xml Recipe Book from Jar"
ModDate="2004-10-09T16:44:35"
BookID="0"
>
<Recipe Name="Pumpkin Seeds" Source="Dorie" Chapter="Appetizers" Cat="" SubCat="" Origin="" UID="" ModDate="2004-03-22T09:19:20">
<IngredientList>
<Ingredient Name="Pumpkin Seeds, unwashed" Amount="2.0" Units="c"/>
<Ingredient Name="Worchestershire Sauce" Amount="0.5" Units="tsp"/>
<Ingredient Name="Butter, melted" Amount="1.5" Units="Tbsp"/>
<Ingredient Name="Johnny's Seasoning" Amount="1.25" Units="tsp"/>
<Ingredient Name="Garlic Powder" Amount="0.5" Units="tsp"/>
</IngredientList>
<ProcessList PrepTime="" TotalTime="">
* Stir all ingredients
* Layout on baking sheet.
* Bake for 1-1/2 to 2 hours at 250 degrees.
</ProcessList>
<Comments>
</Comments>
</Recipe>
<Recipe Name="Banana Bread" Source="Dorie" Chapter="Breads" Cat="Quick Bread" SubCat="" Origin="" UID="" ModDate="2003-12-22T14:51:19">
<IngredientList>
<Ingredient Name="Butter" Amount="0.5" Units="c"/>
<Ingredient Name="Sugar" Amount="1.5" Units="c"/>
<Ingredient Name="Eggs" Amount="2.0" Units="each"/>
<Ingredient Name="Buttermilk" Amount="0.5" Units="c"/>
<Ingredient Name="Bananas" Amount="2.0" Units="large"/>
<Ingredient Name="Flour" Amount="2.0" Units="c"/>
<Ingredient Name="Baking Soda" Amount="1.0" Units="tsp"/>
<Ingredient Name="Nuts or raisons" Amount="0.5" Units="c"/>
</IngredientList>
<ProcessList PrepTime="" TotalTime="">
# Mix butter and sugar.
# Add eggs, buttermilk, and bananas.
# Add flour and baking soda.
# Add nuts/raisons.
# Use a greased pan.
# Bake at 350F for 35-40 minutes (3 little loaf pans) or 70 minutes (big loaf pan).
</ProcessList>
<Comments>
</Comments>
</Recipe>
<Recipe Name="Eggnog Pound Cake" Source="Jill Zimmerman" Chapter="Desserts" Cat="Cakes" SubCat="" Origin="" UID="" ModDate="2004-04-12T12:19:57">
<IngredientList>
<Ingredient Name="Butter, softened" Amount="2.0" Units="Tbsp"/>
<Ingredient Name="Almonds, sliced" Amount="0.5" Units="c"/>
<Ingredient Name="Yellow Cake Mix" Amount="1.0" Units="package"/>
<Ingredient Name="Nutmeg, ground" Amount="0.33333334" Units="tsp"/>
<Ingredient Name="Eggs" Amount="2.0" Units="medium"/>
<Ingredient Name="Eggnog (purchased)" Amount="1.5" Units="c"/>
<Ingredient Name="Butter, melted" Amount="4.0" Units="Tbsp"/>
<Ingredient Name="rum ( or 1/4 tsp rum flavor)" Amount="2.0" Units="Tbsp"/>
</IngredientList>
<ProcessList PrepTime="" TotalTime="">


        Grease a 10in tube or bundt pan with softened butter, press almonds on 
        sides and bottom of pan; set aside.


        In a large bowl, combine cake mix, nutmeg, eggs, eggnog, the melted 
        butter, and rum.


        Using an electric mixer, beat until smooth and creamy (about 4 
        minutes) or beat for about 450 strokes with a wooden spoon. Pount 
        batter into prepared pan.


        Bake at 350 degrees for 45-55 minutes or until a wooden pick inserted 
        into center comes out clean.


        Let cool in pan for 10 minutes; then invert cake onto a rack to cool 
        completely.
</ProcessList>
<Comments>


        Make 10-12 servings
</Comments>
</Recipe>
<Recipe Name="Carrot Cake Cookies" Source="Martha" Chapter="Desserts" Cat="Cookies" SubCat="Carrot Cake" Origin="" UID="" ModDate="2004-03-22T08:59:20">
<IngredientList>
<Ingredient Name="light-brown sugar, packed" Amount="1.0" Units="c"/>
<Ingredient Name="sugar, granulated" Amount="1.0" Units="c"/>
<Ingredient Name="butter, unsalted (room temperature)" Amount="0.5" Units="lb"/>
<Ingredient Name="eggs (room temerature)" Amount="2.0" Units="large"/>
<Ingredient Name="pure vanilla extract" Amount="1.0" Units="tsp"/>
<Ingredient Name="flour, all purpose" Amount="2.0" Units="c"/>
<Ingredient Name="baking soda" Amount="1.0" Units="tsp"/>
<Ingredient Name="baking powder" Amount="1.0" Units="tsp"/>
<Ingredient Name="salt" Amount="0.25" Units="tsp"/>
<Ingredient Name="cinnamon, ground" Amount="1.0" Units="tsp"/>
<Ingredient Name="nutmeg, ground" Amount="0.5" Units="tsp"/>
<Ingredient Name="ginger, ground" Amount="0.5" Units="tsp"/>
<Ingredient Name="oats, rolled old-fashioned" Amount="2.0" Units="c"/>
<Ingredient Name="carrots (finely grated)" Amount="1.5" Units="c"/>
<Ingredient Name="raisons" Amount="1.0" Units="c"/>
<Ingredient Name="Cream Cheese Frosting (Martha's)" Amount="2.0" Units="c"/>
</IngredientList>
<ProcessList PrepTime="" TotalTime="">


        Preheat oven to 350&#176;. Line two baking sheets with Silpat baking mats 
        or parchment paper, and set aside. In the bowl of an electric mixer 
        fitted with the paddle attachment, combine sugars and butter; beat 
        until light and fluffy, 3 to 4 minutes. Add eggs and vanilla, and beat 
        on medium speed until well combined.


        In a large bowl, sift together flour, baking soda, baking powder, 
        salt, cinnamon, nutmeg, and ginger; stir to combine. Gradually add 
        flour to butter mixture; mix on a low speed until just blended. Mix in 
        oats, carrots, and raisins. Chill dough in refrigerator until firm, at 
        least 1 hour.


        Using a 1/2-ounce ice-cream scoop, scoop dough onto prepared baking 
        sheets, leaving 2 inches between cookies. Transfer to oven, and bake 
        until browned and crisped, rotating pan halfway through baking to 
        ensure even color, 12 to 15 minutes. Transfer to a wire rack to cool. 
        Repeat baking process with remaining dough. Once cooled completely, 
        use an offset spatula to spread about 2 teaspoons of cream-cheese 
        filling onto a cookie. Sandwich together with a second cookie. Repeat 
        with remaining cookies. Store in an airtight container for up to 3 
        days in the refrigerator.
</ProcessList>
<Comments>
</Comments>
</Recipe>
<Recipe Name="Peanut Butter Cookies" Source="Martha" Chapter="Desserts" Cat="Cookies" SubCat="Peanut Butter" Origin="" UID="" ModDate="2004-03-22T09:18:16">
<IngredientList>
<Ingredient Name="Butter, unsalted" Amount="8.0" Units="Tbsp"/>
<Ingredient Name="Peanut Butter, smooth" Amount="0.75" Units="c"/>
<Ingredient Name="Sugar, granulated" Amount="0.5" Units="c"/>
<Ingredient Name="Dark Brown Sugar, packed" Amount="0.5" Units="c"/>
<Ingredient Name="Egg, large" Amount="1.0" Units="ea"/>
<Ingredient Name="Vanilla Extract, pure" Amount="0.5" Units="tsp"/>
<Ingredient Name="Flour, all purpose" Amount="1.0" Units="c"/>
<Ingredient Name="Baking Soda" Amount="0.75" Units="tsp"/>
<Ingredient Name="Peanuts, dry roasted (optional)" Amount="2.0" Units="oz"/>
</IngredientList>
<ProcessList PrepTime="" TotalTime="">


        Heat oven to 350 degrees. Line several baking sheets with parchment 
        paper, and set aside.


        In the bowl of an electric mixer fitted with the paddle attachment, 
        cream butter, peanut butter, and both sugars together until light and 
        fluffy. Add egg and vanilla, and mix on medium speed until well 
        combined.


        In a medium mixing bowl, sift flour and baking soda together. Add to 
        the butter mixture, and beat just to combine.


        Scoop out 2 TBSP of dough, shape into a ball, and place on one of the 
        prepared baking sheets. Repeat with remaining dough, placing scoops 3 
        inches apart. Dip the tines of a fork in warm water; press the dough 
        balls lightly with the back of the fork to flatten them slightly (dip 
        the fork back in the water for each dough ball, to prevent sticking). 
        Sprinkle with a few peanuts, if desired.


        Transfer to the oven, and bake until golden brown, 18 to 20 minutes, 
        rotating the baking sheets between the oven shelves halfway through 
        baking. Transfer baking sheets to a wire rack to cool. Store in an 
        airtight container at room temperature up to 1 week.
</ProcessList>
<Comments>
</Comments>
</Recipe>
<Recipe Name="Cream Cheese Frosting" Source="Martha" Chapter="Desserts" Cat="Frosting" SubCat="" Origin="" UID="" ModDate="2004-03-22T09:00:08">
<IngredientList>
<Ingredient Name="cream cheese (room temperature)" Amount="8.0" Units="oz"/>
<Ingredient Name="butter, unsalted (cut into pieces, room temperature)" Amount="8.0" Units="Tbsp"/>
<Ingredient Name="sugar, confectioners'" Amount="1.0" Units="c"/>
<Ingredient Name="pure vanilla extract" Amount="1.0" Units="tsp"/>
</IngredientList>
<ProcessList PrepTime="" TotalTime="">


        Place cream cheese in a medium mixing bowl. Using a rubber spatula, 
        soften cream cheese. Gradually add butter, and continue beating until 
        smooth and well blended. Sift in confectioners&#8217; sugar, and continue 
        beating until smooth. Add vanilla, and stir to combine.
</ProcessList>
<Comments>
    Goes with Martha's Carrot Cake Cookie Recipe.
</Comments>
</Recipe>
<Recipe Name="Beef Stroginoff" Source="Nancy Evans" Chapter="Entrees" Cat="Meat" SubCat="Beef, Traditional" Origin="Russian" UID="" ModDate="2004-09-14T09:32:28">
<IngredientList>
<Ingredient Name="Beef, round steak" Amount="2.0" Units="lb"/>
<Ingredient Name="Onion" Amount="1.0" Units="Medium"/>
<Ingredient Name="Olive Oil" Amount="0.25" Units="c"/>
<Ingredient Name="Sour Cream" Amount="1.0" Units="c"/>
<Ingredient Name="Mushrooms" Amount="0.5" Units="lb"/>
<Ingredient Name="Wine, red" Amount="1.0" Units="c"/>
<Ingredient Name="Flour, multi-purpose" Amount="1.0" Units="c"/>
<Ingredient Name="Beef Consume" Amount="12.0" Units="oz"/>
<Ingredient Name="Noodles, egg, extra wide" Amount="16.0" Units="oz"/>
</IngredientList>
<ProcessList PrepTime="" TotalTime="">


        Slice the Onion, medium fine.
